//
//
//   Application level email contents for confirmation and notification purposes
//
//

//    ***************************************************************************
//
// 1. Register new user confirmation
//    @: client
//
exports.registerConfirmationHtml = (userName) => {
  return `<h3>Sweet to meet you ${userName} :)</h3>
        <p>Thank you for creating user account at tophoneys.com</p>
        <p>Your user profile is accessible after logging in at tophoneys.com or via below link:</p>
        <p><a href="https://tophoneys.com/profile">My Profile</a></p>
        <p>In your profile you may edit your user data as well as find your orders history: whenever you need to find order number or check shipping status</p>
        <p>Your account is 100% free and voluntary</p>
        <p>You may contact us at <a href="mailto:info@tophoneys.com">info@tophoneys.com</a></p>`
}
exports.registerConfirmationTxT = (userName) => {
  return `Sweet to meet you ${userName} :)
  \nThank you for creating user account at tophoneys.com
  \nYour user profile is accessible after logging in at tophoneys.com 
  \nIn your profile you may edit your user data as well as find your orders history: whenever you need to find order number or check shipping status
  \nYou may contact us at info@tophoneys.com
  \nYour account is 100% free and voluntary
  `
}

//    ***************************************************************************
//
// 2. Place order confirmation
//    @: client
//
exports.orderConfirmationHtml = (orderId) => {
  return `<p>Thank you for creating an order.</p>
    <p>Order ID: ${orderId}</p>
    <p>Order details and status: <a href="https://tophoneys.com/order/${orderId}">link</a></p>
    <p>You may pay your order within 2 calendar days.</p>
    <small>This is autogenerated message. Please do not answer it.</small>`
}
exports.orderConfirmationTxt = (orderId) => {
  return `Thank you for creating an order.\n\n
        Order ID:  ${orderId}\n\nOrder details and status: "https://tophoneys.com/order/${orderId}"`
}

//    ***************************************************************************
//
// 3. Purchase confirmation
//    @: client
exports.purchaseConfirmationHtml = (clientName, orderId) => {
  return `<p>${clientName}, thank you for your purchase at TOP HONEYS.</p>
  <p>We usually ship orders within 24 hours from the moment the payment is credited. Sometimes it may take up to 2-4 days.</p>
  <p>Your purchase details and shipping status: <a href="https://tophoneys.com/order/${orderId}">link</a></p>
  <p>We hope to see you soon :).</p>
  <small>This is autogenerated message. Please do not answer it.</small>`
}

exports.purchaseConfirmationTxt = (clientName, orderId) => {
  return `${clientName}, thank you for your purchase at TOP HONEYS.\n\n
        We usually ship orders within 24 hours from the moment the payment is credited. Sometimes it may take up to 2-4 days.
        \n\nYour purchase details and shipping status: "https://tophoneys.com/order/${orderId}"\n\nWe hope to see you soon :).`
}

//    ***************************************************************************
//
// 4. Purchase notification
//    @: vendor
exports.purchaseNotificationHtml = (orderId) => {
  return `<p>New purchase in your shop, order number: ${orderId}</p>
        <p>Order details: <a href="https://tophoneys.com/order/${orderId}">link</a></p>
        <p>Well done! :)</p>`
}
exports.purchaseNotificationTxT = (orderId) => {
  return `New purchase in your shop, order number: ${orderId}\n\nOrder details: 'https://tophoneys.com/order/${orderId}' \n\nWell done! :)`
}

//    ***************************************************************************
//
// 5. New email from contact form notification
//    @: vendor
exports.newEmailNotificationHtml = (senderEmail, senderName) => {
  return `
      <h4>New message from contact form:</h4>
      <p>From: ${senderName}</p>
      <p>email: ${senderEmail}</p>
      <p>Read the full message: <a href="poczta.mydevil.net">open email client</a></p>
      `
}
exports.newEmailNotificationTxt = (senderEmail, senderName) => {
  return `New message from contact form: ${senderName}\n email: ${senderEmail}. \n\nRead the full message: poczta.mydevil.net`
}

//    ***************************************************************************
//
// 6. Success sending email from contact form notification
//    @: client
exports.sendEmailConfirmationHtml = (senderName) => {
  return `
  <h3>Hi ${senderName}</h3>
  <p>Thank you for sending us a message. We will answer as soon as possible.</p>
  <small>This is autogenerated message. Please do not answer it.</small>
  `
}
exports.sendEmailConfirmationTxt = (senderName) => {
  return `Hi, ${senderName}\n Thank you for sending us a message. We will answer as soon as possible. \n\n
  This is autogenerated message. Please do not answer it.`
}
